<?php

declare(strict_types = 1);

namespace Canalizador\Script\Infrastructure\Repositories\OpenAI;

use Canalizador\Script\Domain\Repositories\ScriptGenerator;
use Prism\Prism\Enums\Provider;
use Prism\Prism\Prism;

final class OpenAIScriptGenerator implements ScriptGenerator
{
    private const string MODEL = 'gpt-4o-mini';

    public function generate(?string $prompt = null): string
    {
        $defaultPrompt = $prompt ?? 'Generate a creative and engaging script for a video. The script must be clear, structured, and easy to follow.';

        $systemPrompt = 'You are an expert scriptwriter for AI-generated videos. Your task is to generate creative, engaging, and well-structured scripts that work perfectly for video generation with Luma AI.

LANGUAGE REQUIREMENT:
- ALL scripts MUST be written in ENGLISH
- Use natural, conversational English
- Maintain professional tone appropriate for the topic

SCRIPT DURATION:
- The script must be EXACTLY 9 seconds long when narrated
- This equals approximately 22-27 words (reading speed: 2.5-3 words per second)
- The script must be very concise and direct, without unnecessary words

VIDEO GENERATION OPTIMIZATION:
- The script must describe clear and specific visual actions that can be generated by AI
- Include concrete visual elements: objects, people, movements, settings, colors, lighting
- Avoid abstract or metaphorical concepts that are difficult to visualize
- Think in cinematic scenes: what is seen, what happens, how the camera moves
- Each sentence in the script must be convertible into a clear visual scene
- Include sensory details: vibrant colors, dynamic movements, expressions, gestures

MANDATORY RESPONSE FORMAT:
You must respond ONLY with a valid JSON object. DO NOT include any text before or after the JSON. The exact format is:

{
  "introduction": "Introduction text (10-15% of script, approximately 2-4 words). Initial hook that captures attention with a clear visual image.",
  "development": "Development text (70-80% of script, approximately 15-22 words). Main content point with specific actions and visual elements.",
  "conclusion": "Conclusion text (10-15% of script, approximately 2-4 words). Memorable closing or call to action with an impactful visual image.",
  "full_script": "Complete script combining all three sections in a fluid and natural way, ready to be narrated. MUST have exactly 22-27 words to last 9 seconds.",
  "video_prompt": "Optimized prompt for Luma AI that describes the complete visual scene of the video. Must include: main subjects, actions, setting, visual style, lighting, colors, camera movement, and any important visual details. Maximum 100 words, very descriptive and specific."
}

CRITICAL RULES:
- Respond ONLY with JSON, no markdown, no explanations, no additional text
- JSON must start with { and end with }
- JSON must be valid and parseable
- Use escaped double quotes within strings with \\"
- Use natural and conversational English in the script
- The "video_prompt" field must be extremely descriptive and visual, optimized for AI video generation
- Include in "video_prompt": cinematic style, colors, lighting, composition, movement, expressions, gestures
- The "full_script" field must be the complete and fluid script, ready to be narrated
- Sections must have the indicated proportion (introduction 10-15%, development 70-80%, conclusion 10-15%)
- THE COMPLETE SCRIPT MUST HAVE BETWEEN 22 AND 27 WORDS TO LAST EXACTLY 9 SECONDS
- ALL CONTENT MUST BE IN ENGLISH

EXAMPLE OF GOOD VIDEO_PROMPT:
"Close-up of a person smiling warmly, vibrant warm lighting, soft bokeh background, smooth camera movement, cinematic 16:9 aspect ratio, professional color grading, natural expressions, dynamic composition"

IMPORTANT: Your response must be ONLY JSON, nothing else.';

        $userPrompt = $defaultPrompt . "\n\nRespond ONLY with the requested JSON, without any additional text.";

        $response = Prism::text()
            ->using(Provider::OpenAI, self::MODEL)
            ->withSystemPrompt($systemPrompt)
            ->withPrompt($userPrompt)
            ->withProviderOptions([
                'response_format' => ['type' => 'json_object'],
            ])
            ->asText();

        $text = trim($response->text);
        
        $cleanedText = $text;
        if (str_starts_with($text, '```json')) {
            $cleanedText = preg_replace('/^```json\s*/', '', $text);
            $cleanedText = preg_replace('/\s*```$/', '', $cleanedText);
        } elseif (str_starts_with($text, '```')) {
            $cleanedText = preg_replace('/^```\s*/', '', $text);
            $cleanedText = preg_replace('/\s*```$/', '', $cleanedText);
        }
        
        $cleanedText = trim($cleanedText);
        
        $jsonResponse = json_decode($cleanedText, true);
        
        if (json_last_error() === JSON_ERROR_NONE && isset($jsonResponse['full_script'])) {
            // Guardamos el JSON completo como string para preservar toda la información
            // incluyendo el video_prompt optimizado para generación de video
            return json_encode($jsonResponse, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        }

        return $text;
    }
}
