name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: canalizador_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo, pdo_mysql, xml, ctype, json, tokenizer, fileinfo
          coverage: none
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Copy .env
        run: cp .env.example .env
      - name: Generate app key
        run: php artisan key:generate
      - name: Run migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: canalizador_test
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G
      - name: Run PHP CS Fixer (dry-run)
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run --diff
      - name: Run tests
        run: php artisan test
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: canalizador_test
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
